// Guided introduction: follows the business journey from strategy to rewards. Each step signs in a fictional persona, opens a real page and highlights one area.
export interface TourStep { id: string; title: string; personaId: string | null; path: string; search?: Record<string, unknown>; target: string | null; what: string; why: string; benefit: string }

export const TOUR_STEPS: TourStep[] = [
  { id: 'purpose', title: 'Purpose, audience and benefits', personaId: null, path: '/login', target: 'intro-button',
    what: 'This introduction walks the SCG Capability Suite from strategy to rewards using fictional people and records. Use Next and Back, the list icon to jump to a function, or Escape to leave.',
    why: 'MTP 2027 asks for one modernised capability strategy: skills-first, project-based and AI-powered, scalable across SCG and wired to careers, rewards and P&L impact.',
    benefit: 'Learners get a personal path and a visible career payoff. Managers approve rather than co-design. Sponsors see validated THB impact. The People Committee gets an audited ledger.' },
  { id: 'personas', title: 'Six roles, one platform', personaId: null, path: '/login', target: 'persona-nara',
    what: 'Choose a persona. Each role sees only the records and actions it owns: learner, line manager, BU sponsor, certified coach, Capability Investment Committee and program office.',
    why: 'Role scope keeps the work simple and the counts honest.', benefit: 'Line managers spend hours, not weeks; the platform runs the rest.' },
  { id: 'strategy', title: 'Strategy roadmap', personaId: 'per-supattra', path: '/strategy', target: 'page-header',
    what: 'The program office sees the four sub-plans with live KPIs, the five core components with their three actions each, and where each action lives in the platform.',
    why: 'Every screen traces back to the strategy it serves.', benefit: 'Presenters and reviewers share one map from strategy to feature.' },
  { id: 'agenda', title: 'Value-led capability agenda', personaId: 'per-supattra', path: '/agenda', target: 'page-header',
    what: 'Value pools → critical roles → future skills per BU, with supply versus demand, THB at stake and the build / buy / borrow / bot decision.',
    why: 'Start from strategy, not courses. Fund the biggest value-at-risk gaps first, governed like capex.', benefit: 'Capability spend follows P&L value.' },
  { id: 'blueprints', title: 'Role blueprints', personaId: 'per-supattra', path: '/blueprints', target: 'page-header',
    what: 'Describe a role as the operating model will need it, and Expert Guidance returns the skills it requires, the levels, supply against demand, the THB at risk and a build / buy / borrow / bot call with a cohort plan. Adopt it and the rows join the capability agenda.',
    why: 'MTP 2027 redefines roles before it buys training; the blueprint is how a new role becomes a funded capability line.', benefit: 'A BU head gets a costed capability plan for a role in minutes instead of a quarter.' },
  { id: 'cohorts', title: 'Cohorts from the playbook', personaId: 'per-supattra', path: '/cohorts', target: 'page-header',
    what: 'Create a cohort and the calendar, clinics and gates are generated from the ABC / BCD playbook. Enrol learners to start an assessment wave.',
    why: 'Industrialised playbooks let any BU run the accelerators without redesign.', benefit: 'Scalable and simple to run.' },
  { id: 'assessments', title: 'Assessment waves', personaId: 'per-supattra', path: '/assessments', target: 'page-header',
    what: 'Completion by cohort, each learner\'s priority gaps and a reminder action for those who have not completed.',
    why: 'Baseline the organisation in waves, starting with CBM and CAFI; passport from day one.', benefit: 'Evidence before the first lab day.' },
  { id: 'home', title: 'Learner home and actionable tasks', personaId: 'per-nara', path: '/home', target: 'home-tasks',
    what: 'Nara, a regional sales lead in the CBM turnaround, sees only the actions she can take now. Sidebar badges count the same records.',
    why: 'Tasks derive from record status and cohort dates, so nothing is counted twice and reading an update never completes work.', benefit: 'Work is visible and clears only when the real action is saved.' },
  { id: 'assessment', title: 'Assessment and Expert Guidance', personaId: 'per-nok', path: '/assessment', target: 'assessment-self',
    what: 'Nok rates herself on the critical skills, answers a knowledge check and describes her role. Expert Guidance drafts her gap map and personal path for review.',
    why: 'Phase 0 ranks gaps by skill gap × role relevance × project need.', benefit: 'Personalised journeys from day one; coaching points reach the human coach before clinic 1.' },
  { id: 'journey', title: 'Gap map and weekly guidance', personaId: 'per-nara', path: '/journey', target: 'gap-map',
    what: 'The gap map shows current and target level per skill with the evidence source. Above it, Expert Guidance gives three priorities for the week, coaching points and how to apply skills in role and project.',
    why: 'Re-personalised after every activity; not assessed is never read as zero ability.', benefit: 'Learning time goes where it matters for the BU priority.' },
  { id: 'learning', title: 'Flipped micro-learning', personaId: 'per-nara', path: '/learning', target: 'learning-plan',
    what: 'Modules in order with the reason each was chosen. Opening a module shows objectives, key points, an SCG example, a practice task and a quick check before it can be marked complete.',
    why: 'Core concepts are learned before class so lab time is practice.', benefit: 'Class time becomes 70% practice.' },
  { id: 'labs', title: 'Applied capability labs', personaId: 'per-nara', path: '/labs', target: 'lab-4',
    what: 'Four in-person lab days with agenda, live SCG case, tools, deliverable and pre-work status. Learners check in and record what they take back to work; Day 4 ends with the impact contract.',
    why: 'The tools mastered in labs are the tools applied at work.', benefit: 'Labs hand off directly into the 90-day sprint.' },
  { id: 'contract', title: 'Impact contract and 90-day sprint', personaId: 'per-nara', path: '/contracts/ic-nara', target: 'contract-evidence',
    what: 'Nara\'s contract: share-of-wallet objective, baseline, target, THB value and weekly sprint evidence, with the actions available now at the bottom and Expert Guidance on the sprint above.',
    why: 'Targeted objectives are agreed on Lab Day 4 by learner, manager and sponsor, so ROI is measurable for everyone.', benefit: 'Micro-applications of new skills lift productivity in the flow of work.' },
  { id: 'manager', title: 'Manager decision at the mid-sprint gate', personaId: 'per-somsak', path: '/contracts/ic-tanawat', target: 'contract-actions',
    what: 'Somsak reviews Tanawat\'s week-6 evidence and records scale, pivot or reset. The dialog states what happens next.',
    why: 'Evidence review at week 6 keeps sprints honest.', benefit: 'Management approves on evidence instead of co-designing programs.' },
  { id: 'coaching', title: 'Coaching spine', personaId: 'per-anong', path: '/coaching', target: 'page-header',
    what: 'Certified coaches run asynchronous clinics, respond to Expert Guidance flags, generate a clinic briefing and add notes. Their quality scorecard drives certification.',
    why: 'Fewer man-days with quality tracked; frequent feedback for every learner.', benefit: 'Coaching quality becomes a managed asset.' },
  { id: 'coach-chat', title: 'Expert Guidance, always on', personaId: 'per-nara', path: '/ai-coach', target: 'ai-coach-thread',
    what: 'Learners ask in Thai or English. Answers are short: where you are, the next step with its date, and up to three actions, citing the module they rely on. Stuck learners are flagged to the human coach.',
    why: 'Learning continues after every program, grounded only in approved content.', benefit: 'Navigator, activity guide, content expert, practice partner and progress mirror in one place.' },
  { id: 'practice', title: 'Practice partner', personaId: 'per-mali', path: '/ai-coach', search: { mode: 'practice' }, target: 'practice-panel',
    what: 'Pick a scenario, such as the Gate 2 pitch or a customer discovery interview. Claude plays the counterpart in character and scores every turn against the program rubric, then names the one change to make next time.',
    why: 'Rehearsal is what makes a gate pitch land, and a coach cannot sit with every learner.', benefit: 'Unlimited rehearsal; a session below 3 out of 5 is flagged so the next clinic covers it.' },
  { id: 'ledger', title: 'Sponsor validation and the impact ledger', personaId: 'per-prasert', path: '/ledger', target: 'ledger-stats',
    what: 'Prasert validates claimed THB value. Validated entries are tracked 6–12 months, matched to P&L actuals and sample-audited.',
    why: 'Sponsor-validated value is the second verified currency, feeding reviews, recognition and value-linked incentives.', benefit: 'Capability pays for itself and the P&L feels it.' },
  { id: 'success', title: 'Success cases', personaId: 'per-prasert', path: '/success-cases', target: 'page-header',
    what: 'Every validated improvement and funded concept with the people, badges and THB behind it.',
    why: 'Visible proof stories make the career deal real.', benefit: 'Pull for rollout across BUs.' },
  { id: 'briefs', title: 'Challenge briefs for BCD', personaId: 'per-chatchai', path: '/briefs/cb-logistics', target: 'brief-actions',
    what: 'The committee reviews sponsor-owned P&L briefs under BU themes: approve, return with a note or reject. Approved briefs are assigned to a cohort and a team is formed around them.',
    why: 'Challenges are chosen before Day 1 so the project is the journey.', benefit: 'A curated portfolio managed to a THB pipeline target.' },
  { id: 'gates', title: 'Concept gates 1–3', personaId: 'per-chatchai', path: '/concepts/cp-invoice', target: 'gate-2',
    what: 'Teams advance frame → build → validate and submit evidence packs; the committee records go / pivot / stop, invest / small-scale, or scale under SCG Start the Dot.',
    why: 'Concepts are gated like investments; pre-reads and recorded pitches cut man-days.', benefit: 'Gate-3 winners scale as ventures or internal high-impact initiatives.' },
  { id: 'passport', title: 'Skill passport and the career deal', personaId: 'per-arisa', path: '/passport', target: 'passport-requirements',
    what: 'Arisa\'s outcome-verified badges next to the published requirements for her next level, plus program outcomes (impact rating, top 10%, BCD fast-track) recorded by her manager or sponsor.',
    why: 'Verification tiers make skills a trustworthy common currency; promotion cases cite passport evidence.', benefit: 'Faster, fairer progression and visible growth paths.' },
  { id: 'marketplace', title: 'Talent marketplace', personaId: 'per-arisa', path: '/marketplace', target: 'market-row',
    what: 'Postings show skill requirements against the person\'s evidence: meets, needs development, not assessed. Owners shortlist on verified skills.',
    why: 'Key talent is allocated by verified skills, not titles.', benefit: 'Employees see the immediate payoff of verified skills.' },
  { id: 'performance', title: 'Performance dashboard · AI summary', personaId: 'per-somsak', path: '/performance', target: 'perf-ai',
    what: 'The dashboard opens with a written read of the scorecard: two lines on where the team stands, then two things to do next or investigate. The platform picks the measures and counts; Claude writes the wording, so the same screen always says the same thing.',
    why: 'A leader should not have to read twelve measures to know whether the team is on track.', benefit: 'Every manager, sponsor and coach gets the same instant answer and the same next actions.' },
  { id: 'performance-compare', title: 'Performance dashboard · team vs company', personaId: 'per-somsak', path: '/performance', target: 'perf-compare',
    what: 'Twelve measures across readiness, execution, delivered impact and verified skills, each with its definition and an ahead or behind result. Company view ranks every team with yours highlighted.',
    why: 'Each manager, sponsor and coach should know whether their team is ahead or behind and where to act.', benefit: 'Capability OKRs on leader scorecards, reviewed quarterly, with the evidence one click away.' },
  { id: 'governance', title: 'Impact dashboard', personaId: 'per-chatchai', path: '/governance', target: 'gov-stats',
    what: 'Validated THB impact, pipeline, graduates with verified uplift, BUs onboarded, Gate-1 pass rate, before / after skill uplift and career and rewards triggers. Every number opens its records.',
    why: 'Quarterly impact governance with an audited ledger keeps reported ROI honest.', benefit: 'One evidence base for BU scorecards, the merit cycle and the MTP top KPI.' },
  { id: 'integrations', title: 'Integrations', personaId: 'per-supattra', path: '/integrations', target: 'integration-payroll_rewards',
    what: 'Simulated connectors for HR core talent-profile sync, payroll and rewards merit-cycle export, email and LINE notifications, finance P&L actuals and the Start the Dot hand-off, each with a run log and payload.',
    why: 'One skills data model with HR core as the single source of truth.', benefit: 'Rewards and careers read the same verified data.' },
  { id: 'explain', title: 'Explain this page', personaId: 'per-supattra', path: '/integrations', target: 'explain-fab',
    what: 'On every signed-in page the floating button opens a panel describing purpose, roles, data sources, hand-offs, decisions and limitations for that page.',
    why: 'Client walkthroughs need consistent, verified explanations tied to the real screen.', benefit: 'Anyone can present the platform without memorising the workflows.' },
]
