// Generates supabase/migrations/0002_seed.sql from the TypeScript fixtures so both data sources share one demo scenario.
import { writeFileSync } from 'node:fs'
import { fixtureBundle } from '../src/data/fixtures'

const TABLES: [keyof typeof fixtureBundle, string][] = [
  ['businessUnits', 'business_units'], ['personas', 'personas'], ['skillDomains', 'skill_domains'], ['skills', 'skills'], ['learningModules', 'learning_modules'],
  ['cohorts', 'cohorts'], ['enrollments', 'enrollments'], ['diagnostics', 'diagnostics'], ['diagnosticItems', 'diagnostic_items'], ['learningPlanItems', 'learning_plan_items'],
  ['impactContracts', 'impact_contracts'], ['sprintEvidence', 'sprint_evidence'], ['challengeThemes', 'challenge_themes'], ['challengeBriefs', 'challenge_briefs'], ['teams', 'teams'],
  ['concepts', 'concepts'], ['gateReviews', 'gate_reviews'], ['coachingClinics', 'coaching_clinics'], ['coachingNotes', 'coaching_notes'], ['coachScorecards', 'coach_scorecards'],
  ['passportEntries', 'passport_entries'], ['ledgerEntries', 'ledger_entries'], ['marketplaceRoles', 'marketplace_roles'], ['marketplaceInterests', 'marketplace_interests'],
  ['notifications', 'notifications'], ['coachMessages', 'coach_messages'], ['recordEvents', 'record_events'], ['capabilityGaps', 'capability_gaps'],
]
const JSON_COLS = new Set(['key_dates', 'requirements', 'level_descriptors'])
const snake = (s: string) => s.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)
const lit = (v: unknown, col: string): string => {
  if (v === null || v === undefined) return 'null'
  if (JSON_COLS.has(col)) return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  return `'${String(v).replace(/'/g, "''")}'`
}

let body = ''
for (const [key, table] of TABLES) {
  const rows = fixtureBundle[key] as Record<string, unknown>[]
  if (!rows.length) continue
  const cols = Object.keys(rows[0]).map(snake)
  body += `  insert into public.${table} (${cols.join(', ')}) values\n`
  body += rows.map((r) => `    (${Object.entries(r).map(([k, v]) => lit(v, snake(k))).join(', ')})`).join(',\n') + ';\n\n'
}
const truncate = `  truncate table ${TABLES.map(([, t]) => `public.${t}`).join(', ')}, public.assessments, public.guidance_notes restart identity cascade;\n`
// personas.manager_id is self-referencing; defer FK checks inside the function.
const sql = `-- GENERATED by scripts/gen-seed.ts — do not edit by hand. Fictional demo data.
create or replace function public.seed_demo() returns void language plpgsql security definer set search_path = public as $seed$
begin
${body}end $seed$;

create or replace function public.reset_demo() returns void language plpgsql security definer set search_path = public as $$
begin
${truncate}  perform public.seed_demo();
end $$;

grant execute on function public.seed_demo() to anon, authenticated;
grant execute on function public.reset_demo() to anon, authenticated;

select public.seed_demo();
`
writeFileSync(new URL('../supabase/migrations/0002_seed.sql', import.meta.url), sql)
console.log('seed written', sql.length, 'chars')
