-- GENERATED by scripts/gen-seed.ts — do not edit by hand. Fictional demo data.
create or replace function public.seed_demo() returns void language plpgsql security definer set search_path = public as $seed$
begin
  insert into public.business_units (id, code, name, kind, strategy_onboarded, platform_onboarded) values
    ('bu-cbm', 'CBM', 'Cement & Building Materials (turnaround)', 'turnaround', true, true),
    ('bu-cafi', 'CAFI', 'CAFI Shared Services', 'shared_service', true, true),
    ('bu-scgp', 'SCGP', 'SCG Packaging', 'business', true, false),
    ('bu-scgc', 'SCGC', 'SCG Chemicals', 'business', false, false),
    ('bu-corp', 'CORP', 'Corporate HR (CHR)', 'shared_service', true, true);

  insert into public.personas (id, code, full_name, email, role, bu_id, function_type, job_title, level, manager_id, initials, career_aspiration) values
    ('per-nara', 'nara', 'Nara Wongsuwan', 'nara@demo.scg-capability.example', 'learner', 'bu-cbm', 'business', 'Regional Sales Lead, Building Materials Distribution', 'L3', 'per-kittipong', 'NW', 'Lead a regional commercial team and own dealer P&L'),
    ('per-tanawat', 'tanawat', 'Tanawat Srisuk', 'tanawat@demo.scg-capability.example', 'learner', 'bu-cbm', 'business', 'Plant Operations Supervisor, Saraburi', 'L3', 'per-somsak', 'TS', 'Plant manager within three years'),
    ('per-boonchu', 'boonchu', 'Boonchu Rakdee', 'boonchu@demo.scg-capability.example', 'learner', 'bu-cbm', 'enabling', 'Logistics Planning Supervisor', 'L2', 'per-somsak', 'BR', 'Move into supply-chain analytics'),
    ('per-arisa', 'arisa', 'Arisa Chaiyaporn', 'arisa@demo.scg-capability.example', 'learner', 'bu-cbm', 'enabling', 'Procurement Supervisor', 'L3', 'per-somsak', 'AC', 'Category lead for green materials'),
    ('per-jiraporn', 'jiraporn', 'Jiraporn Suksawat', 'jiraporn@demo.scg-capability.example', 'learner', 'bu-cbm', 'enabling', 'Quality Assurance Supervisor', 'L2', 'per-somsak', 'JS', null),
    ('per-pim', 'pim', 'Pim Rattanakorn', 'pim@demo.scg-capability.example', 'learner', 'bu-cafi', 'enabling', 'Accounts Payable Supervisor', 'L2', 'per-ratree', 'PR', 'Lead a finance automation squad'),
    ('per-krit', 'krit', 'Krit Boonmee', 'krit@demo.scg-capability.example', 'learner', 'bu-cafi', 'enabling', 'IT Service Desk Lead', 'L3', 'per-ratree', 'KB', 'Service delivery manager'),
    ('per-nok', 'nok', 'Nok Saengthong', 'nok@demo.scg-capability.example', 'learner', 'bu-cafi', 'enabling', 'Payroll Operations Supervisor', 'L2', 'per-ratree', 'NS', null),
    ('per-warit', 'warit', 'Warit Thongchai', 'warit@demo.scg-capability.example', 'learner', 'bu-cbm', 'business', 'Business Development Manager, Alternative Fuels', 'L4', 'per-prasert', 'WT', 'Lead a new venture inside SCG'),
    ('per-mali', 'mali', 'Mali Phromma', 'mali@demo.scg-capability.example', 'learner', 'bu-cafi', 'enabling', 'Finance Systems Analyst', 'L3', 'per-ratree', 'MP', 'Product owner for finance platforms'),
    ('per-wichai', 'wichai', 'Wichai Kongkaew', 'wichai@demo.scg-capability.example', 'learner', 'bu-scgc', 'business', 'Incubation Lead, Solar Dealer Leasing', 'L4', 'per-prasert', 'WK', 'Scale the venture to three markets'),
    ('per-kittipong', 'kittipong', 'Kittipong Jaidee', 'kittipong@demo.scg-capability.example', 'line_manager', 'bu-cbm', 'business', 'Sales Manager, Central Region', 'L4', 'per-prasert', 'KJ', null),
    ('per-somsak', 'somsak', 'Somsak Petchsri', 'somsak@demo.scg-capability.example', 'line_manager', 'bu-cbm', 'business', 'Plant Manager, Saraburi', 'L4', 'per-prasert', 'SP', null),
    ('per-ratree', 'ratree', 'Ratree Kaewkla', 'ratree@demo.scg-capability.example', 'line_manager', 'bu-cafi', 'enabling', 'Head of Transaction Services', 'L4', 'per-wanida', 'RK', null),
    ('per-prasert', 'prasert', 'Prasert Vong-anan', 'prasert@demo.scg-capability.example', 'bu_sponsor', 'bu-cbm', 'business', 'Turnaround Sponsor, CBM', 'L5', null, 'PV', null),
    ('per-wanida', 'wanida', 'Wanida Sukjai', 'wanida@demo.scg-capability.example', 'bu_sponsor', 'bu-cafi', 'enabling', 'Head of Shared Services, CAFI', 'L5', null, 'WS', null),
    ('per-suchada', 'suchada', 'Suchada Limpanont', 'suchada@demo.scg-capability.example', 'bu_sponsor', 'bu-scgp', 'business', 'Commercial Director, SCGP', 'L5', null, 'SL', null),
    ('per-anong', 'anong', 'Anong Thepsiri', 'anong@demo.scg-capability.example', 'coach', 'bu-corp', 'enabling', 'Certified Capability Coach', 'L4', 'per-supattra', 'AT', null),
    ('per-decha', 'decha', 'Decha Rungroj', 'decha@demo.scg-capability.example', 'coach', 'bu-corp', 'enabling', 'Certified Capability Coach', 'L4', 'per-supattra', 'DR', null),
    ('per-chatchai', 'chatchai', 'Chatchai Boonyarat', 'chatchai@demo.scg-capability.example', 'committee', 'bu-corp', 'business', 'Chair, Capability Investment Committee', 'L5', null, 'CB', null),
    ('per-ploy', 'ploy', 'Ploy Nimman', 'ploy@demo.scg-capability.example', 'committee', 'bu-corp', 'business', 'Member, Capability Investment Committee (Finance)', 'L5', null, 'PN', null),
    ('per-supattra', 'supattra', 'Supattra Meesuk', 'supattra@demo.scg-capability.example', 'program_office', 'bu-corp', 'enabling', 'Capability Development Lead, CHR', 'L4', null, 'SM', null);

  insert into public.skill_domains (id, code, program, name, description) values
    ('dom-ai', 'AI', 'ABC', 'AI-augmented decision-making', 'Using GenAI copilots and analytics to make faster, better-evidenced decisions in own role.'),
    ('dom-opex', 'OPEX', 'ABC', 'Data-driven OpEx improvement', 'Finding and delivering productivity, cost and quality improvements from own-function data.'),
    ('dom-comm', 'COMM', 'ABC', 'Commercial & green acumen', 'Value-chain, partnership and Green / SVP / HVA economics including CBAM readiness.'),
    ('dom-silo', 'SILO', 'ABC', 'Cross-silo leadership', 'Self-awareness, cross-functional collaboration and organisation design.'),
    ('dom-cust', 'CUST', 'ABC', 'Customer-centric innovation', 'Designing improvements from internal or external customer needs, by BU and channel.'),
    ('dom-chg', 'CHG', 'ABC', 'Change execution', 'Landing practical improvements in the flow of work and sustaining them.'),
    ('dom-bb', 'BB', 'BCD', 'Business building & entrepreneurship', 'Framing, validating and building new concepts as investable businesses.'),
    ('dom-fin', 'FIN', 'BCD', 'Commercial finance & investment casing', 'Business cases, pricing and best / worst case analysis for gate decisions.'),
    ('dom-green', 'GRN', 'BCD', 'Customer-centric & green business design', 'Designing propositions around validated customer and sustainability needs.'),
    ('dom-aistrat', 'AIS', 'BCD', 'AI-augmented strategy', 'Using AI to accelerate research, scenario design and strategic choices.'),
    ('dom-exec', 'EXP', 'BCD', 'Executive presence & storytelling', 'Pitching evidence and asks clearly to executive committees.'),
    ('dom-lead', 'LTC', 'BCD', 'Leading through change', 'Leading cross-BU teams through ambiguity and gate outcomes.');

  insert into public.skills (id, domain_id, code, name, description, critical, premium_eligible, level_descriptors) values
    ('sk-genai', 'dom-ai', 'AI-01', 'GenAI copilot practice', 'Uses approved GenAI tools to draft, analyse and decide in daily work.', true, true, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-decision', 'dom-ai', 'AI-02', 'Evidence-based decision making', 'Frames decisions, weighs evidence and records rationale.', true, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-datastory', 'dom-opex', 'OPEX-01', 'Data storytelling', 'Turns own-function data into a clear improvement narrative.', true, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-opex', 'dom-opex', 'OPEX-02', 'OpEx improvement methods', 'Applies lean / productivity methods to quantify and remove waste.', true, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-valuechain', 'dom-comm', 'COMM-01', 'Value chain & partnership economics', 'Understands where value is created and captured across partners.', true, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-green', 'dom-comm', 'COMM-02', 'Green / CBAM economics', 'Quantifies Green / SVP / HVA options and CBAM exposure.', true, true, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-selfaware', 'dom-silo', 'SILO-01', 'Self-awareness & feedback', 'Seeks and acts on feedback across functions.', false, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-collab', 'dom-silo', 'SILO-02', 'Cross-functional collaboration', 'Aligns priorities and decisions across silos.', true, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-custneeds', 'dom-cust', 'CUST-01', 'Customer needs discovery', 'Elicits and validates internal or external customer needs.', true, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-b2bsales', 'dom-cust', 'CUST-02', 'AI-powered marketing & sales', 'Applies AI to segmentation, lead scoring and offer design.', true, true, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-changeplan', 'dom-chg', 'CHG-01', 'Improvement planning & tracking', 'Defines baseline, target, owner and cadence for an improvement.', true, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-sustain', 'dom-chg', 'CHG-02', 'Sustaining change', 'Embeds new practice through standards, routines and metrics.', false, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-bizbuild', 'dom-bb', 'BB-01', 'Business building', 'Moves a concept from problem framing to validated business model.', true, true, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-invest', 'dom-fin', 'FIN-01', 'Investment casing', 'Builds pricing, cash-flow and best / worst case for a gate decision.', true, true, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-greendesign', 'dom-green', 'GRN-01', 'Green proposition design', 'Designs customer propositions with measurable sustainability value.', true, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-aistrat', 'dom-aistrat', 'AIS-01', 'AI-augmented strategy', 'Uses AI to research markets and stress-test strategic options.', true, true, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-pitch', 'dom-exec', 'EXP-01', 'Executive pitching', 'Presents evidence, asks and risks concisely to executives.', true, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb),
    ('sk-leadchange', 'dom-lead', 'LTC-01', 'Leading cross-BU teams', 'Leads mixed teams through gates, pivots and stops.', true, false, '["Level 1 · Aware: understands concepts and vocabulary; applies with close guidance.","Level 2 · Practising: applies the skill in routine situations in own role with occasional support.","Level 3 · Proficient: applies independently in complex situations and coaches peers.","Level 4 · Leading: sets standards, redesigns work around the skill and delivers measured impact."]'::jsonb);

  insert into public.learning_modules (id, skill_id, code, title, duration_min, format, variant) values
    ('mod-genai-1', 'sk-genai', 'AI-01.1', 'Prompting for analysis (SCG approved tools)', 12, 'micro_video', null),
    ('mod-genai-2', 'sk-genai', 'AI-01.2', 'Drafting proposals with a copilot', 18, 'reading', null),
    ('mod-genai-3', 'sk-genai', 'AI-01.3', 'Checking AI output against source data', 25, 'exercise', null),
    ('mod-decision-1', 'sk-decision', 'AI-02.1', 'Framing a decision in one page', 12, 'micro_video', null),
    ('mod-decision-2', 'sk-decision', 'AI-02.2', 'Weighing evidence and risk', 18, 'reading', null),
    ('mod-decision-3', 'sk-decision', 'AI-02.3', 'Recording rationale for review', 25, 'exercise', null),
    ('mod-datastory-1', 'sk-datastory', 'OPEX-01.1', 'From spreadsheet to story', 12, 'micro_video', null),
    ('mod-datastory-2', 'sk-datastory', 'OPEX-01.2', 'Choosing the right chart for OpEx', 18, 'reading', null),
    ('mod-datastory-3', 'sk-datastory', 'OPEX-01.3', 'Presenting a baseline and target', 25, 'exercise', null),
    ('mod-opex-1', 'sk-opex', 'OPEX-02.1', 'Value-stream mapping in one hour', 12, 'micro_video', null),
    ('mod-opex-2', 'sk-opex', 'OPEX-02.2', 'Quantifying waste in THB', 18, 'reading', null),
    ('mod-opex-3', 'sk-opex', 'OPEX-02.3', 'Daily management routines', 25, 'exercise', null),
    ('mod-valuechain-1', 'sk-valuechain', 'COMM-01.1', 'Where value is created in building materials', 12, 'micro_video', null),
    ('mod-valuechain-2', 'sk-valuechain', 'COMM-01.2', 'Partnership economics', 18, 'reading', null),
    ('mod-valuechain-3', 'sk-valuechain', 'COMM-01.3', 'Dealer economics and margin pools', 25, 'exercise', null),
    ('mod-green-1', 'sk-green', 'COMM-02.1', 'Green / SVP / HVA basics', 12, 'micro_video', null),
    ('mod-green-2', 'sk-green', 'COMM-02.2', 'CBAM exposure for exports', 18, 'reading', null),
    ('mod-green-3', 'sk-green', 'COMM-02.3', 'Pricing green options', 25, 'exercise', null),
    ('mod-selfaware-1', 'sk-selfaware', 'SILO-01.1', 'Feedback that lands', 12, 'micro_video', null),
    ('mod-selfaware-2', 'sk-selfaware', 'SILO-01.2', 'Working styles across functions', 18, 'reading', null),
    ('mod-selfaware-3', 'sk-selfaware', 'SILO-01.3', 'Personal operating rhythm', 25, 'exercise', null),
    ('mod-collab-1', 'sk-collab', 'SILO-02.1', 'Aligning priorities across silos', 12, 'micro_video', null),
    ('mod-collab-2', 'sk-collab', 'SILO-02.2', 'Decision rights in practice', 18, 'reading', null),
    ('mod-collab-3', 'sk-collab', 'SILO-02.3', 'Running a cross-functional stand-up', 25, 'exercise', null),
    ('mod-custneeds-1', 'sk-custneeds', 'CUST-01.1', 'Internal customer interviews', 12, 'micro_video', 'Internal customer · shared services'),
    ('mod-custneeds-2', 'sk-custneeds', 'CUST-01.2', 'External customer interviews (B2B)', 18, 'reading', null),
    ('mod-custneeds-3', 'sk-custneeds', 'CUST-01.3', 'Turning needs into requirements', 25, 'exercise', null),
    ('mod-b2bsales-1', 'sk-b2bsales', 'CUST-02.1', 'AI lead scoring for dealers', 12, 'micro_video', 'B2B external customer · CBM dealers'),
    ('mod-b2bsales-2', 'sk-b2bsales', 'CUST-02.2', 'Segmenting B2B accounts', 18, 'reading', null),
    ('mod-b2bsales-3', 'sk-b2bsales', 'CUST-02.3', 'Designing offers with AI', 25, 'exercise', null),
    ('mod-changeplan-1', 'sk-changeplan', 'CHG-01.1', 'Baseline, target and owner', 12, 'micro_video', null),
    ('mod-changeplan-2', 'sk-changeplan', 'CHG-01.2', 'Weekly evidence cadence', 18, 'reading', null),
    ('mod-changeplan-3', 'sk-changeplan', 'CHG-01.3', 'Impact contract walkthrough', 25, 'exercise', null),
    ('mod-sustain-1', 'sk-sustain', 'CHG-02.1', 'Standard work after the sprint', 12, 'micro_video', null),
    ('mod-sustain-2', 'sk-sustain', 'CHG-02.2', 'Metrics that keep change alive', 18, 'reading', null),
    ('mod-sustain-3', 'sk-sustain', 'CHG-02.3', 'Handing over an improvement', 25, 'exercise', null),
    ('mod-bizbuild-1', 'sk-bizbuild', 'BB-01.1', 'Problem framing with a sponsor', 12, 'micro_video', null),
    ('mod-bizbuild-2', 'sk-bizbuild', 'BB-01.2', 'Business model canvas on a live concept', 18, 'reading', null),
    ('mod-invest-1', 'sk-invest', 'FIN-01.1', 'Pricing and unit economics', 12, 'micro_video', null),
    ('mod-invest-2', 'sk-invest', 'FIN-01.2', 'Best / worst case in one model', 18, 'reading', null),
    ('mod-greendesign-1', 'sk-greendesign', 'GRN-01.1', 'Sustainability value the customer will pay for', 12, 'micro_video', null),
    ('mod-greendesign-2', 'sk-greendesign', 'GRN-01.2', 'Measuring green outcomes', 18, 'reading', null),
    ('mod-aistrat-1', 'sk-aistrat', 'AIS-01.1', 'AI market research sprint', 12, 'micro_video', null),
    ('mod-aistrat-2', 'sk-aistrat', 'AIS-01.2', 'Stress-testing strategy with scenarios', 18, 'reading', null),
    ('mod-pitch-1', 'sk-pitch', 'EXP-01.1', 'Pre-read that decides for you', 12, 'micro_video', null),
    ('mod-pitch-2', 'sk-pitch', 'EXP-01.2', 'Recorded pitch in six minutes', 18, 'reading', null),
    ('mod-leadchange-1', 'sk-leadchange', 'LTC-01.1', 'Forming a cross-BU team fast', 12, 'micro_video', null),
    ('mod-leadchange-2', 'sk-leadchange', 'LTC-01.2', 'Leading after a pivot or stop', 18, 'reading', null);

  insert into public.cohorts (id, program, code, name, bu_id, status, start_date, end_date, key_dates, pipeline_target_thb, seats) values
    ('coh-abc-a0', 'ABC', 'ABC-A0', 'ABC Alpha pilot 2026 (CBM)', 'bu-cbm', 'completed', '2026-04-06', '2026-07-24', '[{"label":"AI skill diagnostic","date":"2026-04-06"},{"label":"Applied capability labs","date":"2026-04-20"},{"label":"Impact sprint","date":"2026-04-27"},{"label":"Mid-sprint gate","date":"2026-06-05"},{"label":"Impact showcase","date":"2026-07-24"}]'::jsonb, 6000000, 24),
    ('coh-abc-l1', 'ABC', 'ABC-L1', 'ABC Lighthouse 1 · CBM turnaround roles', 'bu-cbm', 'sprint', '2026-07-27', '2026-11-13', '[{"label":"AI skill diagnostic","date":"2026-07-27"},{"label":"Flipped micro-learning","date":"2026-07-27"},{"label":"Applied capability labs (4 days)","date":"2026-08-10"},{"label":"Impact sprint starts","date":"2026-08-17"},{"label":"Coaching clinic 1","date":"2026-09-11"},{"label":"Mid-sprint gate","date":"2026-09-25"},{"label":"Coaching clinic 2","date":"2026-10-16"},{"label":"Impact showcase","date":"2026-11-13"}]'::jsonb, 12000000, 30),
    ('coh-abc-l2', 'ABC', 'ABC-L2', 'ABC Lighthouse 2 · CAFI service teams', 'bu-cafi', 'sprint', '2026-08-17', '2026-12-04', '[{"label":"AI skill diagnostic","date":"2026-08-17"},{"label":"Applied capability labs (4 days)","date":"2026-08-31"},{"label":"Impact sprint starts","date":"2026-09-07"},{"label":"Coaching clinic 1","date":"2026-10-02"},{"label":"Mid-sprint gate","date":"2026-10-16"},{"label":"Coaching clinic 2","date":"2026-11-06"},{"label":"Impact showcase","date":"2026-12-04"}]'::jsonb, 9000000, 30),
    ('coh-abc-2027-1', 'ABC', 'ABC-2027-01', 'ABC Batch 1/2027 · enterprise-wide', null, 'planned', '2027-01-11', '2027-04-30', '[{"label":"AI skill diagnostic","date":"2027-01-11"},{"label":"Applied capability labs","date":"2027-01-25"},{"label":"Impact showcase","date":"2027-04-30"}]'::jsonb, 20000000, 60),
    ('coh-bcd-2025', 'BCD', 'BCD-2025', 'BCD Pilot cohort 2025', null, 'scale_up', '2025-06-02', '2025-10-17', '[{"label":"Gate 1","date":"2025-07-28"},{"label":"Gate 2","date":"2025-09-19"},{"label":"Gate 3","date":"2026-03-13"}]'::jsonb, 100000000, 18),
    ('coh-bcd-l1', 'BCD', 'BCD-L1', 'BCD Lighthouse cohort 2026', null, 'building_case', '2026-06-01', '2026-10-23', '[{"label":"Challenge sourcing","date":"2026-06-01"},{"label":"Onboard, diagnose & team up","date":"2026-06-29"},{"label":"Immersion camp (3 days)","date":"2026-07-06"},{"label":"Concept studio sprint","date":"2026-07-13"},{"label":"Field validation","date":"2026-08-03"},{"label":"Gate 1 · Proof of concept","date":"2026-08-24"},{"label":"Commercial build","date":"2026-08-31"},{"label":"Prototype & stress-test","date":"2026-09-28"},{"label":"Gate 2 · CEO investment pitch","date":"2026-10-23"}]'::jsonb, 150000000, 18),
    ('coh-bcd-2027-1', 'BCD', 'BCD-2027-01', 'BCD Batch 1/2027', null, 'framing', '2027-01-18', '2027-05-14', '[{"label":"Challenge brief deadline","date":"2026-10-30"},{"label":"Selection board","date":"2026-11-13"},{"label":"Immersion camp","date":"2027-01-25"}]'::jsonb, 200000000, 24);

  insert into public.enrollments (id, cohort_id, persona_id, status, team_id, coach_id, sponsor_id, manager_id, impact_rating, top_decile, fast_track_bcd) values
    ('enr-arisa', 'coh-abc-a0', 'per-arisa', 'graduated', null, 'per-anong', 'per-prasert', 'per-somsak', 'exceptional', true, true),
    ('enr-jiraporn', 'coh-abc-a0', 'per-jiraporn', 'showcase', null, 'per-anong', 'per-prasert', 'per-somsak', 'strong', false, false),
    ('enr-nara', 'coh-abc-l1', 'per-nara', 'in_sprint', null, 'per-anong', 'per-prasert', 'per-kittipong', null, false, false),
    ('enr-tanawat', 'coh-abc-l1', 'per-tanawat', 'in_sprint', null, 'per-anong', 'per-prasert', 'per-somsak', null, false, false),
    ('enr-boonchu', 'coh-abc-l1', 'per-boonchu', 'in_sprint', null, 'per-anong', 'per-prasert', 'per-somsak', null, false, false),
    ('enr-pim', 'coh-abc-l2', 'per-pim', 'in_sprint', null, 'per-decha', 'per-wanida', 'per-ratree', null, false, false),
    ('enr-krit', 'coh-abc-l2', 'per-krit', 'in_sprint', null, 'per-decha', 'per-wanida', 'per-ratree', null, false, false),
    ('enr-nok', 'coh-abc-l2', 'per-nok', 'in_sprint', null, 'per-decha', 'per-wanida', 'per-ratree', null, false, false),
    ('enr-warit', 'coh-bcd-l1', 'per-warit', 'in_sprint', 'team-a', 'per-decha', 'per-prasert', 'per-prasert', null, false, false),
    ('enr-mali', 'coh-bcd-l1', 'per-mali', 'in_sprint', 'team-b', 'per-decha', 'per-wanida', 'per-ratree', null, false, false),
    ('enr-wichai', 'coh-bcd-2025', 'per-wichai', 'graduated', 'team-d', 'per-anong', 'per-prasert', 'per-prasert', 'exceptional', true, false);

  insert into public.diagnostics (id, enrollment_id, status, completed_at, summary) values
    ('dx-nara', 'enr-nara', 'completed', '2026-07-29T09:00:00+07:00', 'Strongest in customer needs discovery and collaboration. Priority gaps: AI-powered sales, GenAI copilot practice and data storytelling, which map directly to dealer share-of-wallet in the CBM turnaround.'),
    ('dx-tanawat', 'enr-tanawat', 'completed', '2026-07-30T09:00:00+07:00', 'Strong OpEx foundations. Priority gaps: data storytelling, GenAI copilot practice and improvement tracking.'),
    ('dx-boonchu', 'enr-boonchu', 'completed', '2026-07-31T09:00:00+07:00', 'Priority gaps: evidence-based decisions, OpEx methods and sustaining change.'),
    ('dx-arisa', 'enr-arisa', 'completed', '2026-04-07T09:00:00+07:00', 'Priority gaps closed during sprint: green / CBAM economics and value chain economics.'),
    ('dx-jiraporn', 'enr-jiraporn', 'completed', '2026-04-08T09:00:00+07:00', 'Priority gaps: OpEx methods and data storytelling.'),
    ('dx-pim', 'enr-pim', 'completed', '2026-08-19T09:00:00+07:00', 'Priority gaps: GenAI copilot practice, OpEx methods and internal customer needs discovery.'),
    ('dx-krit', 'enr-krit', 'completed', '2026-08-19T09:00:00+07:00', 'Priority gaps: data storytelling, improvement tracking and cross-functional collaboration.'),
    ('dx-nok', 'enr-nok', 'pending', null, null),
    ('dx-warit', 'enr-warit', 'completed', '2026-06-30T09:00:00+07:00', 'Priority gaps: investment casing and executive pitching.'),
    ('dx-mali', 'enr-mali', 'completed', '2026-06-30T09:00:00+07:00', 'Priority gaps: business building and executive pitching.'),
    ('dx-wichai', 'enr-wichai', 'completed', '2025-06-30T09:00:00+07:00', 'All priority gaps closed through Gates 1–3.');

  insert into public.diagnostic_items (id, diagnostic_id, skill_id, current_level, target_level, priority_rank, evidence_source, rationale) values
    ('dxi-nara-b2bsales', 'dx-nara', 'sk-b2bsales', 1, 3, 1, 'ai_inferred', 'Role requires AI-assisted dealer segmentation; CRM activity shows manual lead prioritisation.'),
    ('dxi-nara-genai', 'dx-nara', 'sk-genai', 1, 3, 2, 'knowledge_test', 'Knowledge test 42%. Copilot not yet used in weekly reporting.'),
    ('dxi-nara-datastory', 'dx-nara', 'sk-datastory', 2, 3, 3, 'ai_inferred', 'Reports list numbers without a narrative or baseline.'),
    ('dxi-nara-changeplan', 'dx-nara', 'sk-changeplan', 2, 3, 4, 'manager_input', 'Manager notes improvements start well but lack tracking cadence.'),
    ('dxi-nara-custneeds', 'dx-nara', 'sk-custneeds', 3, 3, null, 'ai_inferred', 'Strength: structured dealer visits and needs capture.'),
    ('dxi-nara-collab', 'dx-nara', 'sk-collab', 3, 3, null, 'manager_input', 'Strength: works well with logistics and credit teams.'),
    ('dxi-nara-valuechain', 'dx-nara', 'sk-valuechain', 2, 3, 5, 'knowledge_test', 'Knowledge test 61%.'),
    ('dxi-nara-green', 'dx-nara', 'sk-green', 1, 2, 6, 'self_declared', 'Self-declared awareness only; low relevance to current role this sprint.'),
    ('dxi-nara-decision', 'dx-nara', 'sk-decision', 2, 3, null, 'ai_inferred', null),
    ('dxi-nara-opex', 'dx-nara', 'sk-opex', 0, 2, null, null, 'Not assessed: no work data available for this skill.'),
    ('dxi-nara-selfaware', 'dx-nara', 'sk-selfaware', 3, 3, null, 'self_declared', null),
    ('dxi-nara-sustain', 'dx-nara', 'sk-sustain', 2, 3, null, 'ai_inferred', null),
    ('dxi-tanawat-datastory', 'dx-tanawat', 'sk-datastory', 1, 3, 1, 'ai_inferred', 'Shift reports contain raw downtime logs without trend or narrative.'),
    ('dxi-tanawat-genai', 'dx-tanawat', 'sk-genai', 1, 3, 2, 'knowledge_test', 'Knowledge test 38%.'),
    ('dxi-tanawat-changeplan', 'dx-tanawat', 'sk-changeplan', 2, 3, 3, 'manager_input', null),
    ('dxi-tanawat-opex', 'dx-tanawat', 'sk-opex', 3, 4, 4, 'ai_inferred', 'Strength to extend to Level 4: lead plant-wide OpEx routine.'),
    ('dxi-tanawat-collab', 'dx-tanawat', 'sk-collab', 2, 3, 5, 'self_declared', null),
    ('dxi-boonchu-decision', 'dx-boonchu', 'sk-decision', 1, 3, 1, 'ai_inferred', null),
    ('dxi-boonchu-opex', 'dx-boonchu', 'sk-opex', 1, 3, 2, 'knowledge_test', null),
    ('dxi-boonchu-sustain', 'dx-boonchu', 'sk-sustain', 1, 2, 3, 'manager_input', null),
    ('dxi-arisa-green', 'dx-arisa', 'sk-green', 1, 3, 1, 'knowledge_test', null),
    ('dxi-arisa-valuechain', 'dx-arisa', 'sk-valuechain', 2, 3, 2, 'ai_inferred', null),
    ('dxi-arisa-changeplan', 'dx-arisa', 'sk-changeplan', 2, 3, 3, 'manager_input', null),
    ('dxi-jiraporn-opex', 'dx-jiraporn', 'sk-opex', 2, 3, 1, 'ai_inferred', null),
    ('dxi-jiraporn-datastory', 'dx-jiraporn', 'sk-datastory', 1, 3, 2, 'knowledge_test', null),
    ('dxi-pim-genai', 'dx-pim', 'sk-genai', 1, 3, 1, 'knowledge_test', 'Knowledge test 45%.'),
    ('dxi-pim-opex', 'dx-pim', 'sk-opex', 2, 3, 2, 'ai_inferred', 'Invoice exceptions handled manually; no waste quantification.'),
    ('dxi-pim-custneeds', 'dx-pim', 'sk-custneeds', 1, 3, 3, 'ai_inferred', 'Internal customer (BU finance) needs not captured systematically.'),
    ('dxi-pim-changeplan', 'dx-pim', 'sk-changeplan', 2, 3, 4, 'manager_input', null),
    ('dxi-krit-datastory', 'dx-krit', 'sk-datastory', 1, 3, 1, 'ai_inferred', null),
    ('dxi-krit-changeplan', 'dx-krit', 'sk-changeplan', 2, 3, 2, 'manager_input', null),
    ('dxi-krit-collab', 'dx-krit', 'sk-collab', 2, 3, 3, 'self_declared', null),
    ('dxi-warit-invest', 'dx-warit', 'sk-invest', 2, 3, 1, 'ai_inferred', null),
    ('dxi-warit-pitch', 'dx-warit', 'sk-pitch', 2, 3, 2, 'manager_input', null),
    ('dxi-warit-bizbuild', 'dx-warit', 'sk-bizbuild', 3, 4, 3, 'ai_inferred', null),
    ('dxi-mali-bizbuild', 'dx-mali', 'sk-bizbuild', 1, 3, 1, 'ai_inferred', null),
    ('dxi-mali-pitch', 'dx-mali', 'sk-pitch', 1, 3, 2, 'knowledge_test', null),
    ('dxi-wichai-bizbuild', 'dx-wichai', 'sk-bizbuild', 4, 4, null, 'ai_inferred', null),
    ('dxi-wichai-invest', 'dx-wichai', 'sk-invest', 3, 3, null, 'ai_inferred', null);

  insert into public.learning_plan_items (id, enrollment_id, module_id, sequence, status, reason) values
    ('lp-nara-1', 'enr-nara', 'mod-b2bsales-1', 1, 'completed', 'Priority gap 1 · B2B dealer variant selected for CBM distribution'),
    ('lp-nara-2', 'enr-nara', 'mod-b2bsales-2', 2, 'completed', 'Priority gap 1'),
    ('lp-nara-3', 'enr-nara', 'mod-genai-1', 3, 'completed', 'Priority gap 2'),
    ('lp-nara-4', 'enr-nara', 'mod-genai-3', 4, 'completed', 'Priority gap 2 · checking output before sharing with dealers'),
    ('lp-nara-5', 'enr-nara', 'mod-datastory-3', 5, 'completed', 'Priority gap 3 · needed for impact contract baseline'),
    ('lp-nara-6', 'enr-nara', 'mod-changeplan-1', 6, 'in_progress', 'Priority gap 4'),
    ('lp-nara-7', 'enr-nara', 'mod-changeplan-2', 7, 'planned', 'Priority gap 4 · weekly evidence cadence'),
    ('lp-nara-8', 'enr-nara', 'mod-valuechain-3', 8, 'planned', 'Priority gap 5 · dealer margin pools'),
    ('lp-nara-9', 'enr-nara', 'mod-custneeds-2', 9, 'skipped', 'Skipped: already at target level (strength)'),
    ('lp-nara-10', 'enr-nara', 'mod-genai-2', 10, 'skipped', 'Skipped: covered in Lab Day 3'),
    ('lp-tanawat-1', 'enr-tanawat', 'mod-datastory-1', 1, 'completed', 'Priority gap 1'),
    ('lp-tanawat-2', 'enr-tanawat', 'mod-datastory-2', 2, 'completed', 'Priority gap 1'),
    ('lp-tanawat-3', 'enr-tanawat', 'mod-genai-1', 3, 'completed', 'Priority gap 2'),
    ('lp-tanawat-4', 'enr-tanawat', 'mod-changeplan-1', 4, 'completed', 'Priority gap 3'),
    ('lp-tanawat-5', 'enr-tanawat', 'mod-opex-3', 5, 'in_progress', 'Extend strength to Level 4'),
    ('lp-tanawat-6', 'enr-tanawat', 'mod-collab-3', 6, 'planned', 'Priority gap 5'),
    ('lp-boonchu-1', 'enr-boonchu', 'mod-decision-1', 1, 'completed', 'Priority gap 1'),
    ('lp-boonchu-2', 'enr-boonchu', 'mod-decision-2', 2, 'in_progress', 'Priority gap 1'),
    ('lp-boonchu-3', 'enr-boonchu', 'mod-opex-1', 3, 'planned', 'Priority gap 2'),
    ('lp-boonchu-4', 'enr-boonchu', 'mod-sustain-1', 4, 'planned', 'Priority gap 3'),
    ('lp-pim-1', 'enr-pim', 'mod-genai-1', 1, 'completed', 'Priority gap 1'),
    ('lp-pim-2', 'enr-pim', 'mod-genai-2', 2, 'in_progress', 'Priority gap 1'),
    ('lp-pim-3', 'enr-pim', 'mod-opex-2', 3, 'planned', 'Priority gap 2 · quantify exception handling waste'),
    ('lp-pim-4', 'enr-pim', 'mod-custneeds-1', 4, 'planned', 'Priority gap 3 · internal customer variant'),
    ('lp-pim-5', 'enr-pim', 'mod-changeplan-1', 5, 'planned', 'Priority gap 4'),
    ('lp-krit-1', 'enr-krit', 'mod-datastory-1', 1, 'completed', 'Priority gap 1'),
    ('lp-krit-2', 'enr-krit', 'mod-changeplan-1', 2, 'completed', 'Priority gap 2'),
    ('lp-krit-3', 'enr-krit', 'mod-collab-1', 3, 'in_progress', 'Priority gap 3'),
    ('lp-arisa-1', 'enr-arisa', 'mod-green-1', 1, 'completed', null),
    ('lp-arisa-2', 'enr-arisa', 'mod-green-2', 2, 'completed', null),
    ('lp-arisa-3', 'enr-arisa', 'mod-valuechain-2', 3, 'completed', null),
    ('lp-arisa-4', 'enr-arisa', 'mod-changeplan-1', 4, 'completed', null),
    ('lp-jiraporn-1', 'enr-jiraporn', 'mod-opex-1', 1, 'completed', null),
    ('lp-jiraporn-2', 'enr-jiraporn', 'mod-datastory-1', 2, 'completed', null),
    ('lp-jiraporn-3', 'enr-jiraporn', 'mod-datastory-3', 3, 'completed', null),
    ('lp-warit-1', 'enr-warit', 'mod-invest-1', 1, 'completed', 'Priority gap 1'),
    ('lp-warit-2', 'enr-warit', 'mod-invest-2', 2, 'in_progress', 'Priority gap 1 · needed for Gate 2 pre-read'),
    ('lp-warit-3', 'enr-warit', 'mod-pitch-1', 3, 'planned', 'Priority gap 2'),
    ('lp-warit-4', 'enr-warit', 'mod-pitch-2', 4, 'planned', 'Priority gap 2'),
    ('lp-mali-1', 'enr-mali', 'mod-bizbuild-1', 1, 'completed', 'Priority gap 1'),
    ('lp-mali-2', 'enr-mali', 'mod-bizbuild-2', 2, 'completed', 'Priority gap 1'),
    ('lp-mali-3', 'enr-mali', 'mod-pitch-1', 3, 'in_progress', 'Priority gap 2');

  insert into public.impact_contracts (id, enrollment_id, learner_id, manager_id, sponsor_id, title, objective_type, description, baseline_value, target_value, unit, target_thb, tools_applied, status, return_reason, mid_gate_decision, mid_gate_note, showcase_summary, validated_value_thb, validated_at, created_at, updated_at) values
    ('ic-nara', 'enr-nara', 'per-nara', 'per-kittipong', 'per-prasert', 'Lift dealer share of wallet in Central Region with AI lead scoring', 'share_of_wallet', 'Use AI lead scoring on the 120 active dealers in Central Region to prioritise weekly visits and offers. Practical improvement: a scored dealer list every Monday, a standard offer pack per segment, and a weekly review with the credit team.', 31, 36, '% share of wallet (top 40 dealers)', 4200000, 'SCG GenAI copilot; CRM export; dealer segmentation template from Lab Day 4', 'active', null, null, null, null, null, null, '2026-08-13T09:00:00+07:00', '2026-08-20T09:00:00+07:00'),
    ('ic-tanawat', 'enr-tanawat', 'per-tanawat', 'per-somsak', 'per-prasert', 'Reduce unplanned kiln downtime at Saraburi Line 2', 'productivity_per_fte', 'Daily downtime story with root-cause tags, GenAI-assisted shift handover and a weekly OpEx routine. Practical improvement: 15% fewer unplanned stops on Line 2.', 42, 36, 'unplanned stop hours per month', 3600000, 'Downtime log analytics; GenAI copilot for handover notes', 'mid_gate_review', null, null, null, null, null, null, '2026-08-13T09:00:00+07:00', '2026-09-12T09:00:00+07:00'),
    ('ic-boonchu', 'enr-boonchu', 'per-boonchu', 'per-somsak', 'per-prasert', 'Cut empty return trips from Saraburi to Bangkok depots', 'cost_to_serve', 'Use route data to pair outbound deliveries with backhaul loads.', 38, 30, '% empty return trips', null, 'Route planning export', 'returned', 'Add the THB value of the target and name the logistics partner who will confirm the baseline. The sprint scope is good.', null, null, null, null, null, '2026-08-13T09:00:00+07:00', '2026-09-08T09:00:00+07:00'),
    ('ic-arisa', 'enr-arisa', 'per-arisa', 'per-somsak', 'per-prasert', 'Switch two packaging categories to lower-CBAM-exposure suppliers', 'cost_to_serve', 'Re-quote two categories with green options and a total-cost model.', 100, 92, 'index of category cost (baseline = 100)', 2000000, 'Total-cost model; CBAM exposure calculator', 'validated', null, 'scale', 'Evidence shows 5% saving already on category 1. Scale to category 2.', 'Delivered THB 2.4M annualised saving across both categories with CBAM exposure reduced by 18%.', 2400000, '2026-07-31T09:00:00+07:00', '2026-04-23T09:00:00+07:00', '2026-07-31T09:00:00+07:00'),
    ('ic-jiraporn', 'enr-jiraporn', 'per-jiraporn', 'per-somsak', 'per-prasert', 'Reduce QA re-test cycle time for cement samples', 'sla_turnaround', 'Standard sample routing and a daily data story of re-test causes.', 3.2, 2, 'days re-test cycle time', 1100000, 'Lab data export; GenAI copilot for cause tagging', 'showcase_review', null, 'scale', 'On track; extend to second lab.', 'Cycle time down to 2.1 days; THB 1.1M avoided rework and overtime (annualised).', null, null, '2026-04-23T09:00:00+07:00', '2026-07-27T09:00:00+07:00'),
    ('ic-pim', 'enr-pim', 'per-pim', 'per-ratree', 'per-wanida', 'Automate invoice exception triage for BU finance teams', 'productivity_per_fte', 'Use GenAI to classify invoice exceptions and route them; agree a service level with two BU finance teams.', 210, 300, 'invoices processed per FTE per week', 1800000, 'SCG GenAI copilot; AP workflow export', 'manager_review', null, null, null, null, null, null, '2026-09-03T09:00:00+07:00', '2026-09-10T09:00:00+07:00'),
    ('ic-krit', 'enr-krit', 'per-krit', 'per-ratree', 'per-wanida', 'Cut service-desk resolution time with a knowledge copilot', 'sla_turnaround', 'Publish a copilot over approved runbooks and track first-contact resolution weekly.', 18, 12, 'hours mean time to resolve', 1500000, 'Runbook copilot; ticket analytics', 'sponsor_review', null, null, null, null, null, null, '2026-09-02T09:00:00+07:00', '2026-09-11T09:00:00+07:00'),
    ('ic-nok', 'enr-nok', 'per-nok', 'per-ratree', 'per-wanida', 'Reduce payroll query turnaround for plant HR teams', 'sla_turnaround', 'Draft only. Diagnostic still pending, so priority skills are not yet selected.', 5, 2, 'days to resolve payroll query', null, null, 'draft', null, null, null, null, null, null, '2026-09-09T09:00:00+07:00', '2026-09-09T09:00:00+07:00');

  insert into public.sprint_evidence (id, contract_id, week_no, title, note, metric_value, created_by, created_at) values
    ('ev-nara-w1', 'ic-nara', 1, 'Scored dealer list produced', 'First AI lead-scoring run on 120 dealers; top 40 identified. Baseline confirmed with credit team.', 31, 'per-nara', '2026-08-21T09:00:00+07:00'),
    ('ev-nara-w2', 'ic-nara', 2, 'Standard offer pack per segment', 'Three offer packs drafted with the copilot and reviewed by marketing.', 31.5, 'per-nara', '2026-08-28T09:00:00+07:00'),
    ('ev-nara-w3', 'ic-nara', 3, 'Weekly review with credit team started', 'Two dealers moved to prioritised credit terms; visit plan follows scores.', 32.4, 'per-nara', '2026-09-04T09:00:00+07:00'),
    ('ev-nara-w4', 'ic-nara', 4, 'Clinic 1 feedback applied', 'Coach suggested tracking share of wallet weekly rather than monthly. Dashboard now weekly.', 33.1, 'per-nara', '2026-09-11T09:00:00+07:00'),
    ('ev-tanawat-w1', 'ic-tanawat', 1, 'Downtime tagging live', 'All Line 2 stops now tagged with root cause.', 42, 'per-tanawat', '2026-08-21T09:00:00+07:00'),
    ('ev-tanawat-w2', 'ic-tanawat', 2, 'Handover notes with copilot', 'Shift handover written with the copilot; 20 minutes saved per shift.', 41, 'per-tanawat', '2026-08-28T09:00:00+07:00'),
    ('ev-tanawat-w3', 'ic-tanawat', 3, 'Weekly OpEx routine', 'Top 3 causes reviewed weekly with maintenance.', 39, 'per-tanawat', '2026-09-04T09:00:00+07:00'),
    ('ev-tanawat-w4', 'ic-tanawat', 4, 'Mid-gate evidence pack submitted', 'Unplanned stop hours trending to 37 hours per month. Requesting scale to Line 1.', 37.5, 'per-tanawat', '2026-09-12T09:00:00+07:00'),
    ('ev-pim-w1', 'ic-pim', 1, 'Exception categories defined', 'Nine categories agreed with two BU finance teams.', 210, 'per-pim', '2026-09-11T09:00:00+07:00');

  insert into public.challenge_themes (id, bu_id, title, description, set_by_id, year) values
    ('th-cbm-fuel', 'bu-cbm', 'Waste reduction & alternative fuels', 'Lower cost per tonne and carbon intensity through alternative fuels and waste-to-value.', 'per-prasert', 2026),
    ('th-cbm-dealer', 'bu-cbm', 'Dealer service excellence', 'Grow share of wallet and cut cost-to-serve across the dealer network.', 'per-prasert', 2026),
    ('th-cafi-auto', 'bu-cafi', 'Automation of transactional finance', 'Raise productivity per FTE and service levels with automation and analytics.', 'per-wanida', 2026),
    ('th-cafi-sla', 'bu-cafi', 'Service level excellence', 'Turnaround times down and satisfaction up for every service team.', 'per-wanida', 2026),
    ('th-scgp-green', 'bu-scgp', 'Green packaging growth', 'New revenue from recyclable and low-carbon packaging in B2B and B2B2C.', 'per-suchada', 2027);

  insert into public.challenge_briefs (id, theme_id, bu_id, sponsor_id, title, challenge_type, problem_statement, success_metric, target_value_thb, constraints, status, cohort_id, committee_note, reviewed_by_id, reviewed_at, created_at, updated_at) values
    ('cb-fuel', 'th-cbm-fuel', 'bu-cbm', 'per-prasert', 'Raise alternative-fuel substitution at two kilns to 35%', 'cost', 'Fuel is the largest controllable cost per tonne. Substitution is stuck at 22% because supply of refuse-derived fuel is unreliable.', 'Fuel cost per tonne; substitution rate', 45000000, null, 'assigned', 'coh-bcd-l1', 'Approved. Strong P&L anchor for the turnaround.', 'per-chatchai', '2026-06-12T09:00:00+07:00', '2026-05-20T09:00:00+07:00', '2026-06-29T09:00:00+07:00'),
    ('cb-invoice', 'th-cafi-auto', 'bu-cafi', 'per-wanida', 'Touchless invoice processing for all BUs', 'productivity', 'Only 40% of invoices are processed without manual touch. BU finance teams escalate exceptions by email.', 'Touchless rate; cost per invoice', 18000000, null, 'assigned', 'coh-bcd-l1', 'Approved with a request to include a service-level commitment.', 'per-chatchai', '2026-06-12T09:00:00+07:00', '2026-05-22T09:00:00+07:00', '2026-06-29T09:00:00+07:00'),
    ('cb-pack', 'th-scgp-green', 'bu-scgp', 'per-suchada', 'Recyclable packaging line for B2B2C food brands', 'growth', 'Food brands ask for recyclable packaging but current offers do not meet cost targets.', 'New revenue; gross margin', 60000000, null, 'assigned', 'coh-bcd-l1', 'Approved.', 'per-chatchai', '2026-06-12T09:00:00+07:00', '2026-05-25T09:00:00+07:00', '2026-06-29T09:00:00+07:00'),
    ('cb-logistics', 'th-cbm-dealer', 'bu-cbm', 'per-prasert', 'Cut cost-to-serve in CBM dealer logistics by 15%', 'cost', 'Small, frequent dealer orders drive high delivery cost. No shared visibility between sales, logistics and dealers.', 'Cost-to-serve per tonne delivered', 35000000, 'Must work with existing transport partners; no new fleet capex in 2027.', 'committee_review', null, null, null, null, '2026-09-02T09:00:00+07:00', '2026-09-08T09:00:00+07:00'),
    ('cb-close', 'th-cafi-auto', 'bu-cafi', 'per-wanida', 'AI-assisted month-end close in five days', 'service', 'Month-end close takes nine working days; BU CFOs want five.', 'Working days to close; adjustments after close', 12000000, null, 'committee_review', null, null, null, null, '2026-09-04T09:00:00+07:00', '2026-09-09T09:00:00+07:00'),
    ('cb-cbam', 'th-cbm-fuel', 'bu-cbm', 'per-prasert', 'Low-carbon cement for CBAM export markets', 'growth', 'European customers will pay a premium for verified low-carbon cement from 2027 but SCG has no certified product.', 'Export revenue; premium per tonne', 80000000, null, 'approved', null, 'Approved. Program office to assign to BCD Batch 1/2027.', 'per-chatchai', '2026-09-11T09:00:00+07:00', '2026-08-28T09:00:00+07:00', '2026-09-11T09:00:00+07:00'),
    ('cb-ordering', 'th-cbm-dealer', 'bu-cbm', 'per-suchada', 'Dealer digital ordering and credit self-service', 'service', 'Dealers order by phone and LINE; credit checks take two days.', 'Order-to-confirm time; dealer satisfaction', null, null, 'returned', null, 'Add a THB target value and confirm which BU P&L owns the benefit. Sponsor and brief BU do not match.', 'per-ploy', '2026-09-10T09:00:00+07:00', '2026-09-01T09:00:00+07:00', '2026-09-10T09:00:00+07:00'),
    ('cb-hrbot', 'th-cafi-sla', 'bu-cafi', 'per-wanida', 'Shared-service copilot for HR and payroll queries', 'service', 'HR service desk answers 6,000 repeat queries a month by email.', 'Queries resolved by copilot; turnaround time', 6000000, null, 'draft', null, null, null, null, '2026-09-12T09:00:00+07:00', '2026-09-12T09:00:00+07:00'),
    ('cb-office', null, 'bu-cafi', 'per-wanida', 'New collaborative office layout for shared services', 'productivity', 'Teams report the current layout limits collaboration.', 'Employee satisfaction', null, null, 'rejected', null, 'Rejected: not anchored to a BU P&L priority. Consider as a facilities request.', 'per-chatchai', '2026-09-05T09:00:00+07:00', '2026-08-30T09:00:00+07:00', '2026-09-05T09:00:00+07:00'),
    ('cb-solar', null, 'bu-scgc', 'per-prasert', 'Solar rooftop leasing through the dealer network', 'growth', 'Dealers have customer access but no clean-energy offer.', 'Recurring revenue; dealers activated', 100000000, null, 'assigned', 'coh-bcd-2025', 'Approved.', 'per-chatchai', '2025-06-10T09:00:00+07:00', '2025-05-20T09:00:00+07:00', '2025-06-30T09:00:00+07:00');

  insert into public.teams (id, cohort_id, name, brief_id, coach_id) values
    ('team-a', 'coh-bcd-l1', 'Team Kiln', 'cb-fuel', 'per-decha'),
    ('team-b', 'coh-bcd-l1', 'Team Touchless', 'cb-invoice', 'per-decha'),
    ('team-c', 'coh-bcd-l1', 'Team Loop', 'cb-pack', 'per-anong'),
    ('team-d', 'coh-bcd-2025', 'Team Sunrise', 'cb-solar', 'per-anong');

  insert into public.concepts (id, team_id, brief_id, cohort_id, title, summary, stage, pipeline_value_thb, validated_value_thb, scale_route, created_at, updated_at) values
    ('cp-fuel', 'team-a', 'cb-fuel', 'coh-bcd-l1', 'RDF supply marketplace for kilns', 'A managed marketplace that contracts municipal and industrial waste streams into refuse-derived fuel with quality guarantees, lifting substitution to 35% at two kilns.', 'build_case', 45000000, null, null, '2026-07-13T09:00:00+07:00', '2026-09-10T09:00:00+07:00'),
    ('cp-invoice', 'team-b', 'cb-invoice', 'coh-bcd-l1', 'Touchless invoicing with a supplier portal', 'Supplier self-service portal plus AI exception handling, targeting 80% touchless processing and a 24-hour exception service level.', 'gate2', 18000000, null, null, '2026-07-13T09:00:00+07:00', '2026-09-13T09:00:00+07:00'),
    ('cp-pack', 'team-c', 'cb-pack', 'coh-bcd-l1', 'Mono-material recyclable pouch for snack brands', 'Field validation showed brands value recyclability but will not absorb a 12% cost premium. Pivoting to a co-branded take-back scheme that lowers net cost.', 'pivot', 25000000, null, null, '2026-07-13T09:00:00+07:00', '2026-08-24T09:00:00+07:00'),
    ('cp-solar', 'team-d', 'cb-solar', 'coh-bcd-2025', 'Solar rooftop leasing via dealers', 'Dealers sell and install leased rooftop solar for SME customers. Scaled under SCG Start the Dot in March 2026.', 'scaled', 100000000, 120000000, 'start_the_dot', '2025-07-01T09:00:00+07:00', '2026-03-13T09:00:00+07:00');

  insert into public.gate_reviews (id, concept_id, gate_no, scheduled_date, evidence_summary, submitted_at, decision, decided_by_id, decided_at, note, validated_value_thb) values
    ('gr-fuel-1', 'cp-fuel', 1, '2026-08-24', 'Evidence pack: 14 waste-stream owners interviewed; two pilot contracts signed; RDF quality test passed at kiln 2.', '2026-08-20T09:00:00+07:00', 'go', 'per-chatchai', '2026-08-24T09:00:00+07:00', 'Go. Build the commercial case with a firm supply plan.', null),
    ('gr-fuel-2', 'cp-fuel', 2, '2026-10-23', null, null, 'pending', null, null, null, null),
    ('gr-invoice-1', 'cp-invoice', 1, '2026-08-24', 'Evidence pack: 30 suppliers tested the portal prototype; exception model 91% accurate on 2,000 invoices.', '2026-08-20T09:00:00+07:00', 'go', 'per-chatchai', '2026-08-24T09:00:00+07:00', 'Go, with a service-level commitment in the case.', null),
    ('gr-invoice-2', 'cp-invoice', 2, '2026-10-23', 'Pre-read submitted early: business case THB 18M annual saving, payback 14 months, best / worst case THB 9M–24M; recorded 6-minute pitch attached.', '2026-09-13T09:00:00+07:00', 'pending', null, null, null, null),
    ('gr-pack-1', 'cp-pack', 1, '2026-08-24', 'Evidence pack: 12 brand interviews; willingness to pay below cost premium.', '2026-08-20T09:00:00+07:00', 'pivot', 'per-chatchai', '2026-08-24T09:00:00+07:00', 'Pivot to the take-back scheme; re-validate with five brands before Gate 2.', null),
    ('gr-solar-1', 'cp-solar', 1, '2025-07-28', 'Evidence pack: 40 SME customers; 8 dealers committed.', '2025-07-24T09:00:00+07:00', 'go', 'per-chatchai', '2025-07-28T09:00:00+07:00', 'Go.', null),
    ('gr-solar-2', 'cp-solar', 2, '2025-09-19', 'Business case THB 100M recurring revenue by year 3.', '2025-09-15T09:00:00+07:00', 'invest', 'per-chatchai', '2025-09-19T09:00:00+07:00', 'Invest THB 30M for small-scale roll-out in two provinces.', null),
    ('gr-solar-3', 'cp-solar', 3, '2026-03-13', 'Two provinces live; THB 120M contracted recurring revenue; 46 dealers activated.', '2026-03-09T09:00:00+07:00', 'scale', 'per-chatchai', '2026-03-13T09:00:00+07:00', 'Scale as a Start the Dot venture.', 120000000);

  insert into public.coaching_clinics (id, cohort_id, clinic_no, scheduled_at, coach_id, topics, briefing_ready) values
    ('cl-l1-1', 'coh-abc-l1', 1, '2026-09-11T09:00:00+07:00', 'per-anong', 'Baselines and weekly evidence; using the copilot for data stories', true),
    ('cl-l1-2', 'coh-abc-l1', 2, '2026-10-16T09:00:00+07:00', 'per-anong', 'Preparing showcase evidence; sustaining change after week 12', false),
    ('cl-l2-1', 'coh-abc-l2', 1, '2026-10-02T09:00:00+07:00', 'per-decha', 'Impact contract quality; internal customer needs', false),
    ('cl-l2-2', 'coh-abc-l2', 2, '2026-11-06T09:00:00+07:00', 'per-decha', 'Showcase preparation', false),
    ('cl-bcd-1', 'coh-bcd-l1', 1, '2026-09-18T09:00:00+07:00', 'per-decha', 'Gate 2 pre-reads and pitch rehearsal', false);

  insert into public.coaching_notes (id, enrollment_id, coach_id, clinic_id, note, ai_flag, created_at) values
    ('cn-1', 'enr-nara', 'per-anong', 'cl-l1-1', 'Move share-of-wallet tracking to weekly; pair with credit team lead on prioritised terms.', 'AI coach flag: learner asked three times about baseline data access in week 3.', '2026-09-11T09:00:00+07:00'),
    ('cn-2', 'enr-tanawat', 'per-anong', 'cl-l1-1', 'Evidence strong. Prepare the mid-gate pack with a clear scale proposal for Line 1.', null, '2026-09-11T09:00:00+07:00'),
    ('cn-3', 'enr-boonchu', 'per-anong', 'cl-l1-1', 'Contract returned by manager; agreed to add THB value with logistics partner by 18 Sep.', 'AI coach flag: no activity in the past 9 days.', '2026-09-11T09:00:00+07:00'),
    ('cn-4', 'enr-warit', 'per-decha', null, 'Gate 2 pre-read draft due 9 Oct. Investment casing module in progress.', 'AI coach flag: best / worst case model not started.', '2026-09-09T09:00:00+07:00');

  insert into public.coach_scorecards (id, coach_id, cohort_id, feedback_frequency, feedback_quality, learner_rating, certified, certified_until) values
    ('cs-anong-l1', 'per-anong', 'coh-abc-l1', 2.4, 4.6, 4.7, true, '2027-06-30'),
    ('cs-anong-a0', 'per-anong', 'coh-abc-a0', 2.1, 4.4, 4.5, true, '2027-06-30'),
    ('cs-decha-l2', 'per-decha', 'coh-abc-l2', 1.8, 4.2, 4.3, true, '2027-03-31'),
    ('cs-decha-bcd', 'per-decha', 'coh-bcd-l1', 2, 4.5, 4.4, true, '2027-03-31');

  insert into public.passport_entries (id, persona_id, skill_id, level, tier, source_type, source_id, badge_code, minted_at) values
    ('pp-arisa-green-ov', 'per-arisa', 'sk-green', 3, 'outcome_verified', 'showcase', 'ic-arisa', 'ABC-A0-COMM-02-L3', '2026-07-31T09:00:00+07:00'),
    ('pp-arisa-valuechain-ov', 'per-arisa', 'sk-valuechain', 3, 'outcome_verified', 'showcase', 'ic-arisa', 'ABC-A0-COMM-01-L3', '2026-07-31T09:00:00+07:00'),
    ('pp-arisa-changeplan-ov', 'per-arisa', 'sk-changeplan', 3, 'outcome_verified', 'showcase', 'ic-arisa', 'ABC-A0-CHG-01-L3', '2026-07-31T09:00:00+07:00'),
    ('pp-arisa-genai-ai', 'per-arisa', 'sk-genai', 2, 'ai_inferred', 'diagnostic', 'dx-arisa', null, '2026-04-07T09:00:00+07:00'),
    ('pp-nara-custneeds-ai', 'per-nara', 'sk-custneeds', 3, 'ai_inferred', 'diagnostic', 'dx-nara', null, '2026-07-29T09:00:00+07:00'),
    ('pp-nara-collab-ai', 'per-nara', 'sk-collab', 3, 'ai_inferred', 'diagnostic', 'dx-nara', null, '2026-07-29T09:00:00+07:00'),
    ('pp-nara-datastory-ai', 'per-nara', 'sk-datastory', 2, 'ai_inferred', 'diagnostic', 'dx-nara', null, '2026-07-29T09:00:00+07:00'),
    ('pp-nara-b2bsales-ai', 'per-nara', 'sk-b2bsales', 1, 'ai_inferred', 'diagnostic', 'dx-nara', null, '2026-07-29T09:00:00+07:00'),
    ('pp-nara-genai-ai', 'per-nara', 'sk-genai', 1, 'ai_inferred', 'diagnostic', 'dx-nara', null, '2026-07-29T09:00:00+07:00'),
    ('pp-nara-changeplan-ai', 'per-nara', 'sk-changeplan', 2, 'ai_inferred', 'diagnostic', 'dx-nara', null, '2026-07-29T09:00:00+07:00'),
    ('pp-nara-valuechain-ai', 'per-nara', 'sk-valuechain', 2, 'ai_inferred', 'diagnostic', 'dx-nara', null, '2026-07-29T09:00:00+07:00'),
    ('pp-nara-green-sd', 'per-nara', 'sk-green', 1, 'self_declared', 'diagnostic', 'dx-nara', null, '2026-07-29T09:00:00+07:00'),
    ('pp-nara-decision-ai', 'per-nara', 'sk-decision', 2, 'ai_inferred', 'diagnostic', 'dx-nara', null, '2026-07-29T09:00:00+07:00'),
    ('pp-tanawat-opex-ai', 'per-tanawat', 'sk-opex', 3, 'ai_inferred', 'diagnostic', 'dx-tanawat', null, '2026-07-30T09:00:00+07:00'),
    ('pp-tanawat-datastory-ai', 'per-tanawat', 'sk-datastory', 1, 'ai_inferred', 'diagnostic', 'dx-tanawat', null, '2026-07-30T09:00:00+07:00'),
    ('pp-tanawat-genai-ai', 'per-tanawat', 'sk-genai', 1, 'ai_inferred', 'diagnostic', 'dx-tanawat', null, '2026-07-30T09:00:00+07:00'),
    ('pp-wichai-bizbuild-ov', 'per-wichai', 'sk-bizbuild', 4, 'outcome_verified', 'gate', 'gr-solar-3', 'BCD-2025-BB-01-L4', '2026-03-13T09:00:00+07:00'),
    ('pp-wichai-invest-ov', 'per-wichai', 'sk-invest', 3, 'outcome_verified', 'gate', 'gr-solar-2', 'BCD-2025-FIN-01-L3', '2025-09-19T09:00:00+07:00'),
    ('pp-wichai-pitch-ov', 'per-wichai', 'sk-pitch', 3, 'outcome_verified', 'gate', 'gr-solar-2', 'BCD-2025-EXP-01-L3', '2025-09-19T09:00:00+07:00'),
    ('pp-wichai-leadchange-ov', 'per-wichai', 'sk-leadchange', 3, 'outcome_verified', 'gate', 'gr-solar-3', 'BCD-2025-LTC-01-L3', '2026-03-13T09:00:00+07:00'),
    ('pp-warit-bizbuild-ai', 'per-warit', 'sk-bizbuild', 3, 'ai_inferred', 'diagnostic', 'dx-warit', null, '2026-06-30T09:00:00+07:00'),
    ('pp-warit-invest-ai', 'per-warit', 'sk-invest', 2, 'ai_inferred', 'diagnostic', 'dx-warit', null, '2026-06-30T09:00:00+07:00'),
    ('pp-warit-pitch-ai', 'per-warit', 'sk-pitch', 2, 'ai_inferred', 'diagnostic', 'dx-warit', null, '2026-06-30T09:00:00+07:00'),
    ('pp-warit-bizbuild-ov', 'per-warit', 'sk-bizbuild', 3, 'outcome_verified', 'gate', 'gr-fuel-1', 'BCD-L1-BB-01-L3', '2026-08-24T09:00:00+07:00'),
    ('pp-mali-bizbuild-ov', 'per-mali', 'sk-bizbuild', 2, 'outcome_verified', 'gate', 'gr-invoice-1', 'BCD-L1-BB-01-L2', '2026-08-24T09:00:00+07:00'),
    ('pp-mali-pitch-ai', 'per-mali', 'sk-pitch', 1, 'ai_inferred', 'diagnostic', 'dx-mali', null, '2026-06-30T09:00:00+07:00'),
    ('pp-pim-genai-ai', 'per-pim', 'sk-genai', 1, 'ai_inferred', 'diagnostic', 'dx-pim', null, '2026-08-19T09:00:00+07:00'),
    ('pp-pim-opex-ai', 'per-pim', 'sk-opex', 2, 'ai_inferred', 'diagnostic', 'dx-pim', null, '2026-08-19T09:00:00+07:00'),
    ('pp-krit-datastory-ai', 'per-krit', 'sk-datastory', 1, 'ai_inferred', 'diagnostic', 'dx-krit', null, '2026-08-19T09:00:00+07:00'),
    ('pp-krit-changeplan-ai', 'per-krit', 'sk-changeplan', 2, 'ai_inferred', 'diagnostic', 'dx-krit', null, '2026-08-19T09:00:00+07:00');

  insert into public.ledger_entries (id, persona_id, bu_id, source_type, source_id, title, objective_type, claimed_value_thb, validated_value_thb, sponsor_id, status, validated_at, tracking_until, audit_note, created_at) values
    ('lg-arisa', 'per-arisa', 'bu-cbm', 'impact_contract', 'ic-arisa', 'Packaging category switch (CBAM exposure)', 'cost_to_serve', 2400000, 2400000, 'per-prasert', 'validated', '2026-07-31T09:00:00+07:00', '2027-07-31', null, '2026-07-27T09:00:00+07:00'),
    ('lg-jiraporn', 'per-jiraporn', 'bu-cbm', 'impact_contract', 'ic-jiraporn', 'QA re-test cycle time', 'sla_turnaround', 1100000, null, 'per-prasert', 'pending_validation', null, '2027-07-31', null, '2026-07-27T09:00:00+07:00'),
    ('lg-solar', 'per-wichai', 'bu-scgc', 'concept', 'cp-solar', 'Solar rooftop leasing via dealers (Gate 3)', 'revenue_uplift', 120000000, 120000000, 'per-prasert', 'audited', '2026-03-13T09:00:00+07:00', '2027-03-13', 'Annual sample audit June 2026: contracted revenue confirmed against signed leases.', '2026-03-13T09:00:00+07:00');

  insert into public.marketplace_roles (id, title, bu_id, kind, description, open_until, owner_id, requirements) values
    ('mr-incubation', 'Incubation lead · RDF supply marketplace (if funded at Gate 2)', 'bu-cbm', 'role', 'Lead the small-scale implementation for six months with a P&L owner.', '2026-11-15', 'per-prasert', '[{"skillId":"sk-bizbuild","minLevel":3},{"skillId":"sk-invest","minLevel":3},{"skillId":"sk-leadchange","minLevel":2}]'::jsonb),
    ('mr-dealer-analytics', 'Dealer analytics gig · Central Region (3 months)', 'bu-cbm', 'gig', 'Build the weekly share-of-wallet dashboard for all regions using the lighthouse template.', '2026-10-31', 'per-kittipong', '[{"skillId":"sk-datastory","minLevel":2},{"skillId":"sk-b2bsales","minLevel":2},{"skillId":"sk-genai","minLevel":2}]'::jsonb),
    ('mr-cafi-squad', 'Finance automation squad member', 'bu-cafi', 'project', 'Six-month squad delivering touchless invoicing for two BUs.', '2026-12-15', 'per-wanida', '[{"skillId":"sk-opex","minLevel":2},{"skillId":"sk-genai","minLevel":2},{"skillId":"sk-custneeds","minLevel":2}]'::jsonb),
    ('mr-green-category', 'Category lead · Green materials procurement', 'bu-cbm', 'role', 'Own supplier strategy for low-CBAM-exposure categories.', '2026-10-15', 'per-prasert', '[{"skillId":"sk-green","minLevel":3},{"skillId":"sk-valuechain","minLevel":3},{"skillId":"sk-sustain","minLevel":2}]'::jsonb);

  insert into public.marketplace_interests (id, role_id, persona_id, created_at, status) values
    ('mi-1', 'mr-green-category', 'per-arisa', '2026-08-15T09:00:00+07:00', 'shortlisted'),
    ('mi-2', 'mr-incubation', 'per-warit', '2026-09-01T09:00:00+07:00', 'expressed');

  insert into public.notifications (id, persona_id, kind, title, body, link, read_at, created_at) values
    ('nt-1', 'per-nara', 'update', 'Impact contract approved by sponsor', 'Prasert Vong-anan approved your impact contract. The sprint is active from 17 August.', '/contracts/ic-nara', '2026-08-20T09:00:00+07:00', '2026-08-20T09:00:00+07:00'),
    ('nt-2', 'per-nara', 'update', 'Clinic 1 note from your coach', 'Anong Thepsiri added a coaching note after clinic 1.', '/contracts/ic-nara', null, '2026-09-11T09:00:00+07:00'),
    ('nt-3', 'per-nara', 'update', 'Mid-sprint gate on 25 September', 'Submit your evidence pack by 23 September so your manager and sponsor can review.', '/contracts/ic-nara', null, '2026-09-12T09:00:00+07:00'),
    ('nt-4', 'per-kittipong', 'update', 'Nara logged week 4 evidence', 'Share of wallet is trending at 33.1% against a 36% target.', '/contracts/ic-nara', null, '2026-09-11T09:00:00+07:00'),
    ('nt-5', 'per-somsak', 'update', 'Tanawat submitted the mid-gate evidence pack', 'Decide scale, pivot or reset before 25 September.', '/contracts/ic-tanawat', null, '2026-09-12T09:00:00+07:00'),
    ('nt-6', 'per-prasert', 'update', 'Gate 2 pre-read available for Touchless invoicing', 'Team Touchless submitted their Gate 2 case early.', '/concepts/cp-invoice', null, '2026-09-13T09:00:00+07:00'),
    ('nt-7', 'per-chatchai', 'update', 'Gate 2 pre-read submitted early', 'Team Touchless submitted the Gate 2 business case and recorded pitch.', '/concepts/cp-invoice', null, '2026-09-13T09:00:00+07:00'),
    ('nt-8', 'per-arisa', 'update', 'Badges minted to your skill passport', 'Three outcome-verified badges were minted after your showcase. Your talent profile is updated.', '/passport', '2026-08-01T09:00:00+07:00', '2026-07-31T09:00:00+07:00'),
    ('nt-9', 'per-arisa', 'update', 'Shortlisted for Category lead · Green materials', 'Prasert Vong-anan shortlisted you based on verified passport skills.', '/marketplace', null, '2026-08-20T09:00:00+07:00'),
    ('nt-10', 'per-wanida', 'update', 'Brief returned by the committee', 'The committee returned "Dealer digital ordering" with a request for a THB target.', '/briefs/cb-ordering', null, '2026-09-10T09:00:00+07:00'),
    ('nt-11', 'per-supattra', 'update', 'Brief approved: Low-carbon cement for CBAM markets', 'Assign the approved brief to BCD Batch 1/2027.', '/briefs/cb-cbam', null, '2026-09-11T09:00:00+07:00'),
    ('nt-12', 'per-warit', 'update', 'Gate 2 pre-read due 9 October', 'Your coach flagged that the best / worst case model has not started.', '/concepts/cp-fuel', null, '2026-09-09T09:00:00+07:00'),
    ('nt-13', 'per-anong', 'update', 'AI coach flags for clinic 2', 'Two learners in ABC Lighthouse 1 are flagged for follow-up.', '/coaching', null, '2026-09-12T09:00:00+07:00');

  insert into public.coach_messages (id, persona_id, sender, lang, content, cited_module_id, created_at) values
    ('cm-1', 'per-nara', 'user', 'th', 'สัปดาห์นี้ต้องส่งอะไรบ้างสำหรับ mid-sprint gate?', null, '2026-09-12T09:00:00+07:00'),
    ('cm-2', 'per-nara', 'coach', 'th', 'สำหรับ Mid-sprint gate วันที่ 25 กันยายน คุณต้องส่ง evidence pack ภายในวันที่ 23 กันยายน ประกอบด้วย 1) ค่า baseline และค่าปัจจุบันของ share of wallet 2) หลักฐานการทำงานรายสัปดาห์ 5 สัปดาห์ 3) ข้อเสนอว่าจะ scale, pivot หรือ reset ดูตัวอย่างได้ในโมดูล CHG-01.2 "Weekly evidence cadence"', 'mod-changeplan-2', '2026-09-12T09:00:00+07:00'),
    ('cm-3', 'per-nara', 'user', 'en', 'How do I present the baseline so the sponsor trusts it?', null, '2026-09-12T09:00:00+07:00'),
    ('cm-4', 'per-nara', 'coach', 'en', 'State the data source (CRM export, confirmed with the credit team on 21 August), the period (12 weeks before the sprint), and the calculation. Then show the weekly trend from 31.0% to 33.1% next to the 36% target. Module OPEX-01.3 "Presenting a baseline and target" has a one-slide template.', 'mod-datastory-3', '2026-09-12T09:00:00+07:00');

  insert into public.record_events (id, record_type, record_id, actor_id, action, from_status, to_status, note, created_at) values
    ('rev-1', 'impact_contract', 'ic-nara', 'per-nara', 'submit', 'draft', 'manager_review', null, '2026-08-14T09:00:00+07:00'),
    ('rev-2', 'impact_contract', 'ic-nara', 'per-kittipong', 'manager_approve', 'manager_review', 'sponsor_review', 'Good scope. Keep the credit team involved.', '2026-08-17T09:00:00+07:00'),
    ('rev-3', 'impact_contract', 'ic-nara', 'per-prasert', 'sponsor_approve', 'sponsor_review', 'active', 'Approved. THB 4.2M target agreed.', '2026-08-20T09:00:00+07:00'),
    ('rev-4', 'impact_contract', 'ic-tanawat', 'per-tanawat', 'submit', 'draft', 'manager_review', null, '2026-08-14T09:00:00+07:00'),
    ('rev-5', 'impact_contract', 'ic-tanawat', 'per-somsak', 'manager_approve', 'manager_review', 'sponsor_review', null, '2026-08-17T09:00:00+07:00'),
    ('rev-6', 'impact_contract', 'ic-tanawat', 'per-prasert', 'sponsor_approve', 'sponsor_review', 'active', null, '2026-08-19T09:00:00+07:00'),
    ('rev-7', 'impact_contract', 'ic-tanawat', 'per-tanawat', 'submit_mid_gate', 'active', 'mid_gate_review', 'Requesting scale to Line 1.', '2026-09-12T09:00:00+07:00'),
    ('rev-8', 'impact_contract', 'ic-boonchu', 'per-boonchu', 'submit', 'draft', 'manager_review', null, '2026-09-04T09:00:00+07:00'),
    ('rev-9', 'impact_contract', 'ic-boonchu', 'per-somsak', 'return', 'manager_review', 'returned', 'Add the THB value of the target and name the logistics partner who will confirm the baseline.', '2026-09-08T09:00:00+07:00'),
    ('rev-10', 'impact_contract', 'ic-pim', 'per-pim', 'submit', 'draft', 'manager_review', null, '2026-09-10T09:00:00+07:00'),
    ('rev-11', 'impact_contract', 'ic-krit', 'per-krit', 'submit', 'draft', 'manager_review', null, '2026-09-09T09:00:00+07:00'),
    ('rev-12', 'impact_contract', 'ic-krit', 'per-ratree', 'manager_approve', 'manager_review', 'sponsor_review', null, '2026-09-11T09:00:00+07:00'),
    ('rev-13', 'impact_contract', 'ic-arisa', 'per-prasert', 'validate', 'showcase_review', 'validated', 'THB 2.4M validated against category invoices.', '2026-07-31T09:00:00+07:00'),
    ('rev-14', 'impact_contract', 'ic-jiraporn', 'per-jiraporn', 'submit_showcase', 'active', 'showcase_review', null, '2026-07-27T09:00:00+07:00'),
    ('rev-15', 'challenge_brief', 'cb-logistics', 'per-prasert', 'submit', 'draft', 'committee_review', null, '2026-09-08T09:00:00+07:00'),
    ('rev-16', 'challenge_brief', 'cb-close', 'per-wanida', 'submit', 'draft', 'committee_review', null, '2026-09-09T09:00:00+07:00'),
    ('rev-17', 'challenge_brief', 'cb-cbam', 'per-chatchai', 'approve', 'committee_review', 'approved', 'Approved. Program office to assign to BCD Batch 1/2027.', '2026-09-11T09:00:00+07:00'),
    ('rev-18', 'challenge_brief', 'cb-ordering', 'per-ploy', 'return', 'committee_review', 'returned', 'Add a THB target value and confirm which BU P&L owns the benefit.', '2026-09-10T09:00:00+07:00'),
    ('rev-19', 'challenge_brief', 'cb-office', 'per-chatchai', 'reject', 'committee_review', 'rejected', 'Not anchored to a BU P&L priority.', '2026-09-05T09:00:00+07:00'),
    ('rev-20', 'concept', 'cp-invoice', 'per-mali', 'submit_gate_evidence', 'build_case', 'gate2', 'Gate 2 pre-read and recorded pitch submitted.', '2026-09-13T09:00:00+07:00'),
    ('rev-21', 'concept', 'cp-fuel', 'per-chatchai', 'gate_decision', 'gate1', 'build_case', 'Gate 1: Go.', '2026-08-24T09:00:00+07:00'),
    ('rev-22', 'concept', 'cp-pack', 'per-chatchai', 'gate_decision', 'gate1', 'pivot', 'Gate 1: Pivot to take-back scheme.', '2026-08-24T09:00:00+07:00'),
    ('rev-23', 'ledger_entry', 'lg-arisa', 'per-prasert', 'validate', 'pending_validation', 'validated', null, '2026-07-31T09:00:00+07:00'),
    ('rev-24', 'ledger_entry', 'lg-solar', 'per-supattra', 'audit', 'validated', 'audited', 'Annual sample audit June 2026.', '2026-06-20T09:00:00+07:00');

end $seed$;

create or replace function public.reset_demo() returns void language plpgsql security definer set search_path = public as $$
begin
  truncate table public.business_units, public.personas, public.skill_domains, public.skills, public.learning_modules, public.cohorts, public.enrollments, public.diagnostics, public.diagnostic_items, public.learning_plan_items, public.impact_contracts, public.sprint_evidence, public.challenge_themes, public.challenge_briefs, public.teams, public.concepts, public.gate_reviews, public.coaching_clinics, public.coaching_notes, public.coach_scorecards, public.passport_entries, public.ledger_entries, public.marketplace_roles, public.marketplace_interests, public.notifications, public.coach_messages, public.record_events restart identity cascade;
  perform public.seed_demo();
end $$;

grant execute on function public.seed_demo() to anon, authenticated;
grant execute on function public.reset_demo() to anon, authenticated;

select public.seed_demo();
